platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: alpine

inputs:
- name: github-repo
  path: github-repo/app

run:
  path: github-repo/tasks/npm_install.sh