resources:
- name: github-repo
  type: git
  source:
    uri: https://github.com/raashidjunaid1/try-concourse.git
    branch: master

jobs:
# - name: test
#   plan:
#   - get: github-repo
#     trigger: true
#   - task: unit test
#     config:
#       platform: linux
#       image_resource:
#         type: docker-image
#         source:
#           repository: node
#           tag: alpine
        
#       inputs:
#       - name: github-repo

#       caches:
#       - path: github-repo/app/node_modules

#       run:
#         path: sh
#         args:
#         - -exec
#         - |
#             cd github-repo/app
#             npm install
#             npm run test

# - name: build
#   plan:
#   - get: github-repo
#   - task: build
#     config:
#       platform: linux
#       image_resource:
#         type: docker-image
#         source:
#           repository: node
#           tag: alpine
    
#       inputs:
#       - name: github-repo

#       outputs:
#       - name: public

#       caches:
#       - path: github-repo/app/node_modules

#       run:
#         path: sh
#         args:
#         - -exec
#         - |
#             cd github-repo/app
#             npm install
#             npm run build
#             find public


- name: deploy
  plan:
  - get: github-repo
    # passed: [build]
    trigger: true
  - task: deploy
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: google/cloud-sdk
          tag: alpine

      params:
        AUTH_KEY : ((json-key))

      caches:
      - path: github-repo/app/node_modules

      inputs:
      - name: github-repo
      # - name: public
      run:
        path: sh
        args:
        - -exec
        - |
            # find public
            apk add --update nodejs nodejs-npm
            cd github-repo/app
            npm install
            npm run build
            echo $AUTH_KEY > encrypted_key.txt
            base64 -d encrypted_key.txt > myfile.json
            gcloud auth activate-service-account --key-file myfile.json
            gcloud config set project kubes-241612
            gcloud app deploy -q