resources:
- name: github-repo
  type: git
  source:
    uri: https://github.com/raashidjunaid1/try-concourse.git
    branch: master

# - name: site-image
#   type: docker-image
#   source:
#     email: raashidjunaid1@gmail.com 
#     username: raashidjunaid1
#     password: 2Udontwannaknow
#     repository: raashidjunaid1/site-image

jobs:
- name: npm-install
  plan:
  - get: github-repo
  - task: npm-install
    file: github-repo/tasks/npm_install_task.yml

- name: npm-test
  plan:
  - get: github-repo
    passed:
    - npm-install
  - task: npm-test
    file: github-repo/tasks/npm_test_task.yml