resources:
- name: app
  type: git
  source:
    uri: https://github.com/raashidjunaid1/try-concourse.git
    branch: master

jobs:
- name: npm-install
  plan:
  - get: app
  - task: npm-install
    file: app/tasks/npm_install_task.yml