resources:
- name: gatsby-site
  type: git
  source:
    uri: https://github.com/raashidjunaid1/try-concourse.git
    branch: master

jobs:
- name: npm-install
  plan:
  - get: gatsby-site
  - task: npm-install
    file: gatsby-site/tasks/npm_install_task.yml