resources:
- name: github-repo
  type: git
  source:
    uri: https://github.com/raashidjunaid1/try-concourse.git
    branch: master

jobs:
- name: npm-install
  plan:
  - get: github-repo
  - task: npm-install
    file: github-repo/tasks/npm_install_task.yml

- name: npm-test
  plan:
  - get: github-repo
  - task: npm-test
    file: github-repo/tasks/npm_test_task.yml